### ISSUE TITLE
[Question] how is the children prop meant to be used?

### ISSUE THREAD

**Issue by moallim10** [fabio-alss-freitas/react-native-animated-splash-screen#11]
Hello!

I've been getting an issue these past few days. I can't seem to add more than two elements inside the AnimatedSplash component. How can I use the children prop to render more than one element? 

Thanks in advance!

**Comment by fabio-alss-freitas** [comment]
Hello @moallim10 !

Can you show your code as example?

**Comment by moallim10** [comment]
Yes of course!

**AppNavigator.js**
`return (
    <AppearanceProvider>
    <NavigationContainer theme={scheme === 'dark' ? darkTheme : lightTheme}>
    {user && (
      <AnimatedSplash
      translucent={true}
      isLoaded={isLoading}
      logoImage={require("../assets/images/icon/LogoForSplash.png")}
      backgroundColor={Colors.primary}
      logoHeight={150}
      logoWidth={150}
      >
        {userProfile && (<AppTabsNavigator />)}
        {!userProfile && <CreateUserNavigator />}
      </AnimatedSplash> 
    )}
    {!user && <AuthStackNavigator /> }
     </NavigationContainer>
    </AppearanceProvider>
  );`

`**App.js**
`const [fontLoaded, setFontLoaded] = useState(false);

  if (!fontLoaded) {
    return (
      <AppLoading
        startAsync={fetchFonts}
        onFinish={() => {
          setFontLoaded(true);
        }}
      />
    );
  }
  return (
    <Provider store={store}>
      <AppNavigator />
    </Provider>
  );
}`

**Error**
`Warning: Failed prop type: Invalid prop 'children' of type 'array' supplied to 'AnimatedSplash', expected a single React
Element.
* [native code]:null in __expoConsoleLog
- node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:197:6 in registerError
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:84:8 in errorImpl
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:63:4 in console.error
- node_modules\expo\build\environment\muteWarnings.fx.js:27:4 in error
- node_modules\prop-types\checkPropTypes.js:20:6 in printWarning
- node_modules\prop-types\checkPropTypes.js:82:22 in checkPropTypes
- node_modules\react\cjs\react.development.js:1875:18 in validatePropTypes
- node_modules\react\cjs\react.development.js:2059:21 in createElementWithValidation
* navigation\AppNavigator.js:56:4 in AppNavigator
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:10989:26 in renderWithHooks
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:13385:34 in updateFunctionComp
onent
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:22002:24 in beginWork$$1
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20871:23 in performUnitOfWork
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20848:38 in workLoopSync
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20456:22 in performSyncWorkOnR
oot
* [native code]:null in performSyncWorkOnRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5703:31 in runWithPriority$arg
ument_1
- node_modules\react-native\node_modules\scheduler\cjs\scheduler.development.js:818:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5698:21 in flushSyncCallbackQu
eueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5686:28 in flushSyncCallbackQu
eue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19845:30 in scheduleUpdateOnFi
ber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11880:16 in dispatchAction
* [native code]:null in dispatchAction
- node_modules\@firebase\util\dist\index.cjs.js:1024:12 in Sha1.prototype.compress_
- node_modules\@firebase\util\dist\index.cjs.js:1141:20 in Sha1.prototype.update
- node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
- node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:135:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:183:16 in _callImmediatesPass
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:446:30 in callImmediates
* [native code]:null in callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:396:6 in __callImmediates
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:144:6 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:373:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:143:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
`

**Comment by moallim10** [comment]
Hey there - I'm closing the issue because after debugging, I've solved my error!
