### ISSUE TITLE
Animated

### ISSUE THREAD

**Issue by fabriciosautner** [fabio-alss-freitas/react-native-animated-splash-screen#3]
Hello,

Would it be possible to add a gif, video or a lottie component?

**Comment by JazibJafri** [comment]
It's already possible to add gif, just add these into your dependencies in:

**`android/app/build.gradle`, (not inside `android/build.gradle`)**
```
implementation "com.facebook.fresco:fresco:2.0.0"
implementation "com.facebook.fresco:animated-gif:2.0.0"
```

Like
```
dependencies {
    implementation "com.facebook.react:react-native:+"  // From node_modules
    ...
    implementation "com.facebook.fresco:fresco:2.0.0"  // <---- add this
    implementation "com.facebook.fresco:animated-gif:2.0.0" // <---- add this
    ...
}
```

Then you can use it like any other image

```jsx
<AnimatedSplash
    isLoaded={false}
    logoImage={require('./loader.gif')}
    logoHeight={100}
    logoWidth={100}
>
{children}
</AnimatedSplash>

```

**Comment by fabio-alss-freitas** [comment]
> It's already possible to add gif, just add these into your dependencies in:
> 
> **`android/app/build.gradle`, (not inside `android/build.gradle`)**
> 
> ```
> implementation "com.facebook.fresco:fresco:2.0.0"
> implementation "com.facebook.fresco:animated-gif:2.0.0"
> ```
> 
> Like
> 
> ```
> dependencies {
>     implementation "com.facebook.react:react-native:+"  // From node_modules
>     ...
>     implementation "com.facebook.fresco:fresco:2.0.0"  // <---- add this
>     implementation "com.facebook.fresco:animated-gif:2.0.0" // <---- add this
>     ...
> }
> ```
> 
> Then you can use it like any other image
> 
> ```js-jsx
> <AnimatedSplash
>     isLoaded={false}
>     logoImage={require('./loader.gif')}
>     logoHeight={100}
>     logoWidth={100}
> >
> {children}
> </AnimatedSplash>
> ```

Exactly! Thank you @JazibJafri.

And also, I will change the code to accept a custom component instead of a Image component. It will be released in few days.

**Comment by fabriciosautner** [comment]
> > It's already possible to add gif, just add these into your dependencies in:
> > **`android/app/build.gradle`, (not inside `android/build.gradle`)**
> > ```
> > implementation "com.facebook.fresco:fresco:2.0.0"
> > implementation "com.facebook.fresco:animated-gif:2.0.0"
> > ```
> > 
> > 
> > Like
> > ```
> > dependencies {
> >     implementation "com.facebook.react:react-native:+"  // From node_modules
> >     ...
> >     implementation "com.facebook.fresco:fresco:2.0.0"  // <---- add this
> >     implementation "com.facebook.fresco:animated-gif:2.0.0" // <---- add this
> >     ...
> > }
> > ```
> > 
> > 
> > Then you can use it like any other image
> > ```
> > <AnimatedSplash
> >     isLoaded={false}
> >     logoImage={require('./loader.gif')}
> >     logoHeight={100}
> >     logoWidth={100}
> > >
> > {children}
> > </AnimatedSplash>
> > ```
> 
> Exactly! Thank you @JazibJafri.
> 
> And also, I will change the code to accept a custom component instead of an Image component. It will be released in few days.

Perfect!

Being able to use a component would be great. So we can render something more animated.
