### ISSUE TITLE
App stop on Splash screen  

### ISSUE THREAD

**Issue by davStar** [fabio-alss-freitas/react-native-animated-splash-screen#8]
### Issue Description:

I have installed the react-animated-splash-screen. At the launch of the application the Splash screen appears and nothing happen then...
Test has been done on IOS simulator IOS11 and not on Android yet.

The following warning appear on the bottom of the splash screen :

`Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Can't find variable: loadAsync`

### Code Description:

On **App.js** 
```
`
import AnimatedSplash from 'react-native-animated-splash-screen';
....

const AppNavigator = createSwitchNavigator(
  {
  Auth: AuthStack,
  Sinister: SinisterStack,
  CivicMain: CivicContainer,
  },
  {
    initialRouteName: 'Auth',
    mode:'modal',

  
  }
);


const AppContainer = createAppContainer(AppNavigator);


export default class App extends React.Component {
 

  
    state = {
      isLoaded: false,

    }
    
 

  async componentDidMount() {
    await loadAsync()
    this.setState({ isLoaded: true })
  }

 

  render() {
    return (

        <AnimatedSplash
          translucent={true}
          isLoaded={this.state.isLoaded}
          logoImage={require("./assets/img/IconBlanc.png")}
          backgroundColor={"#ffffff"}
          logoHeight={200}
          logoWidth={200}
        >
          <AppContainer />
        </AnimatedSplash>

    );
  }
}
`
```

### Expected Behaviour

After the Splash Screen the initial Route name   'Auth' should appear.

### Environment:
React Native 0.62 (Not Expo)
React Navigation 4.x
MacOS 10.15.22 

Needing your help and support thank you!

**Comment by fabio-alss-freitas** [comment]
> ### Issue Description:
> I have installed the react-animated-splash-screen. At the launch of the application the Splash screen appears and nothing happen then...
> Test has been done on IOS simulator IOS11 and not on Android yet.
> 
> The following warning appear on the bottom of the splash screen :
> 
> `Possible Unhandled Promise Rejection (id: 0): ReferenceError: Can't find variable: loadAsync`
> 
> ### Code Description:
> On **App.js**
> 
> ```
> `
> import AnimatedSplash from 'react-native-animated-splash-screen';
> ....
> 
> const AppNavigator = createSwitchNavigator(
>   {
>   Auth: AuthStack,
>   Sinister: SinisterStack,
>   CivicMain: CivicContainer,
>   },
>   {
>     initialRouteName: 'Auth',
>     mode:'modal',
> 
>   
>   }
> );
> 
> 
> const AppContainer = createAppContainer(AppNavigator);
> 
> 
> export default class App extends React.Component {
>  
> 
>   
>     state = {
>       isLoaded: false,
> 
>     }
>     
>  
> 
>   async componentDidMount() {
>     await loadAsync()
>     this.setState({ isLoaded: true })
>   }
> 
>  
> 
>   render() {
>     return (
> 
>         <AnimatedSplash
>           translucent={true}
>           isLoaded={this.state.isLoaded}
>           logoImage={require("./assets/img/IconBlanc.png")}
>           backgroundColor={"#ffffff"}
>           logoHeight={200}
>           logoWidth={200}
>         >
>           <AppContainer />
>         </AnimatedSplash>
> 
>     );
>   }
> }
> `
> ```
> 
> ### Expected Behaviour
> After the Splash Screen the initial Route name 'Auth' should appear.
> 
> ### Environment:
> React Native 0.62 (Not Expo)
> React Navigation 4.x
> MacOS 10.15.22
> 
> Needing your help and support thank you!

Hi, @davStar !

The loadAsync function is an example of use with a async function, showing where all your asynchronous loading should be.
`async componentDidMount() {
    await loadAsync(); // <------------- JUST EXAMPLE, PLEASE REMOVE!
    this.props.setAppLoaded();
  }`
